apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  index.html: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
    user-interface.properties: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>It's my site - Dmitry ILL</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>It's my site - Dmitry ILL</h1>
    <p>Hello!</p>
    </body>
    </html>
